# Generated by Django 2.2.8 on 2019-12-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Reply', verbose_name='Replies'),
        ),
    ]
