# Generated by Django 2.2.8 on 2019-12-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191219_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
