# Generated by Django 2.2.8 on 2019-12-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_reply_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-approved'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='deleted',
            new_name='marked_as_deleted',
        ),
    ]
