# Generated by Django 2.2.8 on 2019-12-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191220_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(blank=True, to='posts.Reply', verbose_name='Replies'),
        ),
    ]
